name: increase build-number
on:
  schedule:
   - cron: "0 6 * * 0/4"
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
        name: Checkout
      - name: increase build number
        run:
          python recipe/increase_build_number.py
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'looooo'
          git config --global user.email 'sppedflyer@gmail.com'
          git commit -am "+=1"
          git push
